/*ADD COLUMN TABLES SEYCI - TRASLADOSEYCI - REEVALUACION*/

alter table seyci add column MODIFICADO_POR varchar(50);
alter table seyci add column MODIFICADO_FECHA varchar(50);
alter table TRASLADOSEYCI add column MODIFICADO_POR varchar(50);
alter table TRASLADOSEYCI add column MODIFICADO_FECHA varchar(50);
alter table reevaluacion add column INGRESADO_POR varchar(50);
alter table reevaluacion add column INGRESADO_FECHA varchar(50);
alter table reevaluacion add column MODIFICADO_POR varchar(50);
alter table reevaluacion add column MODIFICADO_FECHA varchar(50);

/* Changelog 1.0 
--Cambios en SP_LISTAR_DETALLE_SOLICITUD  se quito duplicidad de EXP
*/
DROP PROCEDURE  IF EXISTS SP_LISTAR_DETALLE_SOLICITUD;
CREATE PROCEDURE `SP_LISTAR_DETALLE_SOLICITUD`(
IN INIDSOLICITUD VARCHAR(10)
)
BEGIN

      
      /*SELECT 
      IDSOLICITUD,
      NUMEROEXPEDIENTE,
      CUSPP,
      PRIMERNOMBRE,
      SEGUNDONOMBRE,
      PRIMERAPELLIDO,
      SEGUNDOAPELLIDO 
      FROM SOLICITUD WHERE IDSOLICITUD=INIDSOLICITUD;*/

      SELECT
      SE.`EXP`,
      SE.`CUSPP`,
      SE.`PRIMERNOMBRE`,
      SE.`SEGUNDONOMBRE`,
      SE.`PRIMERAPELLIDO`,
      SE.`SEGUNDOAPELLIDO`,
      SE.`FECHANACEVALUADO`,
      SE.`EMAILAFI`,
      SE.`SEXO`,
      SE.`TELEFONOAFI`,
      ''  ESTADOCIVIL,
      SE.`DIRECCIONAFI`,
      SE.`DEPARTAMENTOAFI`,
      (SELECT IDDEPARTAMENTO FROM DEPARTAMENTOS WHERE DEPARTAMENTO=SE.`DEPARTAMENTOAFI`)IDDEPARTAMENTO,
       SE.`PROVINCIAAFI`,
      (SELECT IDPROVINCIA from PROVINCIAS WHERE IDDEPARTAMENTO = (SELECT IDDEPARTAMENTO FROM DEPARTAMENTOS WHERE DEPARTAMENTO=SE.`DEPARTAMENTOAFI`) AND PROVINCIA= SE.`PROVINCIAAFI`)IDPROVINCIA,
      SE.`DISTRITOAFI`,
      (SELECT IDDISTRITO FROM DISTRITOS WHERE IDPROVINCIA=(SELECT IDPROVINCIA from PROVINCIAS WHERE IDDEPARTAMENTO = (SELECT IDDEPARTAMENTO FROM DEPARTAMENTOS WHERE DEPARTAMENTO=SE.`DEPARTAMENTOAFI`) AND PROVINCIA= SE.`PROVINCIAAFI`) AND DISTRITO=SE.`DISTRITOAFI`)IDDISTRITO
      FROM SEYCI SE
      WHERE SE.`EXP` = INIDSOLICITUD;
    

END;
/*
--Cambios en SP_ACTUALIZAR_SEYCI_DG  add MODIFICADO_POR y MODIFICADO_FECHA
*/
DROP PROCEDURE  IF EXISTS SP_ACTUALIZAR_SEYCI_DG;
CREATE PROCEDURE `SP_ACTUALIZAR_SEYCI_DG`(
IN INIDSOLICITUD VARCHAR(100),
IN INCUSPP VARCHAR(100),
IN INPRIMERNOMBRE VARCHAR(100),
IN INSEGUNDONOMBRE VARCHAR(100),
IN INPRIMERAPELLIDO VARCHAR(100),
IN INSEGUNDOAPELLIDO  VARCHAR(100),
IN INFECHANACIMIENTO VARCHAR(100),
IN INCORREO VARCHAR(100),
IN INSEXO VARCHAR(100),
IN INTELEFONO VARCHAR(100),
IN INDIRECCIONAFI VARCHAR(100),
IN INDEPARTAMENTOAFI VARCHAR(100),
IN INPROVINCIAFI VARCHAR(100),
IN INDISTRITOAFI VARCHAR(100),
IN MODIFICADOUSU VARCHAR(50)
)
BEGIN

     UPDATE SEYCI SET
     CUSPP = INCUSPP,
     PRIMERNOMBRE = INPRIMERNOMBRE,
     SEGUNDONOMBRE = INSEGUNDONOMBRE,
     PRIMERAPELLIDO = INPRIMERAPELLIDO,
     SEGUNDOAPELLIDO = INSEGUNDOAPELLIDO,
     FECHANACEVALUADO = INFECHANACIMIENTO,
     EMAILAFI = INCORREO,
     SEXO = (SELECT CASE WHEN INSEXO = '1' THEN 'Masculino' ELSE 'Femenino'  END AS SEXO),
     TELEFONOAFI = INTELEFONO,
     DIRECCIONAFI = INDIRECCIONAFI,
     DEPARTAMENTOAFI  = (SELECT DEPARTAMENTO FROM DEPARTAMENTOS WHERE IDDEPARTAMENTO=INDEPARTAMENTOAFI),
     PROVINCIAAFI = (SELECT PROVINCIA FROM PROVINCIAS WHERE IDPROVINCIA=INPROVINCIAFI),
     DISTRITOAFI = (SELECT DISTRITO FROM DISTRITOS WHERE IDDISTRITO = INDISTRITOAFI),
     MODIFICADO_POR = MODIFICADOUSU,
     MODIFICADO_FECHA = NOW()
     WHERE EXP= INIDSOLICITUD;
END;
/*
--Cambios en SP_ACTUALIZAR_SEYCI_TAB add  MODIFICADO_POR y MODIFICADO_FECHA
*/
DROP PROCEDURE  IF EXISTS SP_ACTUALIZAR_SEYCI_TAB
CREATE PROCEDURE `SP_ACTUALIZAR_SEYCI_TAB`(
IN INIDSOLICITUD VARCHAR(100),
IN INEJECUTIVAAGENCIA VARCHAR(100),
IN INTIPOSOLICITUD VARCHAR(100),
IN INTIPODEEVALUADO VARCHAR(100),
IN INPRIMERNOMBRE VARCHAR(100),
IN INSEGUNDONOMBRE VARCHAR(100),
IN INPRIMERAPELLIDO VARCHAR(100),
IN INSEGUNDOAPELLIDO VARCHAR(100),
IN INFECHANACEVALUADO VARCHAR(100),
IN INFECHASECCIONI VARCHAR(100),
IN INFECHAENVIOCOMAFP VARCHAR(100),
IN INOBSERVACIONESSEYCI VARCHAR(100),
IN MODIFICADOUSU VARCHAR(50)
)
BEGIN

     UPDATE SEYCI SET
     EJECUTIVAAGENCIA = INEJECUTIVAAGENCIA,
     TIPOSOLICITUD  = INTIPOSOLICITUD,
     TIPODEEVALUADO = INTIPODEEVALUADO,
     PRIMERNOMBRE = INPRIMERNOMBRE,
     SEGUNDONOMBRE = INSEGUNDONOMBRE,
     PRIMERAPELLIDO = INPRIMERAPELLIDO,
     SEGUNDOAPELLIDO = INSEGUNDOAPELLIDO,
     FECHANACEVALUADO = INFECHANACEVALUADO,
     FECHASECCIONI = INFECHASECCIONI,
     FECHAENVIOCOMAFP = INFECHAENVIOCOMAFP,
     OBSERVACIONESSEYCI = INOBSERVACIONESSEYCI,
     MODIFICADO_POR = MODIFICADOUSU,
     MODIFICADO_FECHA = NOW()
     WHERE EXP= INIDSOLICITUD;
END;
/*
--Cambios en SP_LISTAR_TRASLADO_SEYCI OBTENIENDO NOMBRE DEPARTAMENTO de ORIGEN - DESTINO
*/
DROP PROCEDURE  IF EXISTS SP_LISTAR_TRASLADO_SEYCI;
CREATE PROCEDURE `SP_LISTAR_TRASLADO_SEYCI`(
IN INIDSOLICITUD VARCHAR(10)
)
BEGIN
     SELECT
        t.IDTRASLADO,
        t.NROEXPSEYCI ,
        t.NROTRASLADO ,
        t.FECHACITA ,
        t.ACOMPANANTE ,
        t.TIPO ,
        (SELECT DEPARTAMENTO FROM DEPARTAMENTOS WHERE IDDEPARTAMENTO=t.ORIGEN) `ORIGEN`,
        (SELECT DEPARTAMENTO FROM DEPARTAMENTOS WHERE IDDEPARTAMENTO=t.DESTINO) `DESTINO`,
        t.FECHAAPROBACION ,
        t.MONEDA1 ,
        t.TIPOMOVILIDAD ,
        t.MONTOMOVILIDAD ,
        t.MONEDA2 ,
        t.DIASALIMENTACION,
        t.MONTOALIMENTACION ,
        t.MONTO3 ,
        t.DIASALOJAMIENTO ,
        t.MONTOALOJAMIENTO ,
        t.MONTOEXTRAMEDICOS ,
        t.TOTALGASTO ,
        t.EJECUTIVA ,
        t.ANALISTA  
     FROM TRASLADOSEYCI t 
     WHERE t.NROEXPSEYCI= INIDSOLICITUD;
    
END;
/*
--Cambios en SP_INSERT_UPDATE_TRASLADO  add MODIFICADO_POR y MODIFICADO_FECHA 
*/
DROP PROCEDURE  IF EXISTS SP_INSERT_UPDATE_TRASLADO
CREATE PROCEDURE `SP_INSERT_UPDATE_TRASLADO`(
IN INNROEXPSEYCI VARCHAR(100) ,
IN INNROTRASLADO VARCHAR(100) ,
IN INFECHACITA VARCHAR(100) ,
IN INACOMPANANTE VARCHAR(100) ,
IN INTIPO VARCHAR(100) ,
IN INORIGEN VARCHAR(100) ,
IN INDESTINO VARCHAR(100) ,
IN INFECHAAPROBACION VARCHAR(100) ,
IN INMONEDA1 VARCHAR(100) ,
IN INTIPOMOVILIDAD VARCHAR(100) ,
IN INMONTOMOVILIDAD VARCHAR(100) ,
IN INMONEDA2 VARCHAR(100) ,
IN INDIASALIMENTACION VARCHAR(100) ,
IN INMONTOALIMENTACION VARCHAR(100) ,
IN INMONTO3 VARCHAR(100) ,
IN INDIASALOJAMIENTO VARCHAR(100) ,
IN INMONTOALOJAMIENTO VARCHAR(100) ,
IN INMONTOEXTRAMEDICOS VARCHAR(100) ,
IN INTOTALGASTO VARCHAR(100) ,
IN INEJECUTIVA VARCHAR(100) ,
IN INANALISTA  VARCHAR(100),
IN MODIFICADOUSU VARCHAR(50)
)
BEGIN

     DECLARE CONTADOR INT;
   
     SELECT COUNT(*) INTO CONTADOR FROM TRASLADOSEYCI WHERE NROEXPSEYCI = INNROEXPSEYCI;

    #IF ( CONTADOR = 0 ) THEN

     INSERT INTO TRASLADOSEYCI(
     NROEXPSEYCI,
     NROTRASLADO,
     FECHACITA,
     ACOMPANANTE,
     TIPO,
     ORIGEN,
     DESTINO,
     FECHAAPROBACION,
     MONEDA1,
     TIPOMOVILIDAD,
     MONTOMOVILIDAD,
     MONEDA2,
     DIASALIMENTACION,
     MONTOALIMENTACION,
     MONTO3,
     DIASALOJAMIENTO,
     MONTOALOJAMIENTO,
     MONTOEXTRAMEDICOS,
     TOTALGASTO,
     EJECUTIVA,
     ANALISTA,
     MODIFICADO_POR,
     MODIFICADO_FECHA)
     VALUES(
     INNROEXPSEYCI,
     INNROTRASLADO,
     INFECHACITA,
     INACOMPANANTE,
     INTIPO,
     INORIGEN,
     INDESTINO,
     INFECHAAPROBACION,
     INMONEDA1,
     INTIPOMOVILIDAD,
     INMONTOMOVILIDAD,
     INMONEDA2,
     INDIASALIMENTACION,
     INMONTOALIMENTACION,
     INMONTO3,
     INDIASALOJAMIENTO,
     INMONTOALOJAMIENTO,
     INMONTOEXTRAMEDICOS,
     INTOTALGASTO,
     INEJECUTIVA,
     INANALISTA,
     MODIFICADOUSU,
     NOW());

    /*ELSE

      UPDATE TRASLADOSEYCI SET
            NROTRASLADO = INNROTRASLADO  ,
            FECHACITA = INFECHACITA  ,
            ACOMPANANTE = INACOMPANANTE  ,
            TIPO = INTIPO  ,
            ORIGEN =  INORIGEN  ,
            DESTINO = INDESTINO  ,
            FECHAAPROBACION = INFECHAAPROBACION  ,
            MONEDA1 = INMONEDA1  ,
            TIPOMOVILIDAD = INTIPOMOVILIDAD  ,
            MONTOMOVILIDAD = INMONTOMOVILIDAD  ,
            MONEDA2 = INMONEDA2  ,
            DIASALIMENTACION = INDIASALIMENTACION  ,
            MONTOALIMENTACION = INMONTOALIMENTACION  ,
            MONTO3 = INMONTO3  ,
            DIASALOJAMIENTO = INDIASALOJAMIENTO  ,
            MONTOALOJAMIENTO = INMONTOALOJAMIENTO  ,
            MONTOEXTRAMEDICOS = INMONTOEXTRAMEDICOS  ,
            TOTALGASTO = INTOTALGASTO  ,
            EJECUTIVA = INEJECUTIVA  ,
            ANALISTA =  INANALISTA
     WHERE NROEXPSEYCI= INNROEXPSEYCI;

    END IF;*/

   END;
/*
--Cambios en SP_INSERT_UPDATE_REEVALUACION add INGRESADO_POR , INGRESADO_FECHA , MODIFICADO_POR y MODIFICADO_FECHA 
*/
DROP PROCEDURE  IF EXISTS SP_INSERT_UPDATE_REEVALUACION;
CREATE PROCEDURE `SP_INSERT_UPDATE_REEVALUACION`(
IN INNROEXPSEYCI VARCHAR(100) ,
IN INFECHAINGRESOBENEFICIOS VARCHAR(100) ,
IN INTIPODOCUMENTO VARCHAR(100) ,
IN INFECHAEVALUACION VARCHAR(100) ,
IN INANALISTA VARCHAR(100) ,
IN INFECHANOTIFICACION VARCHAR(100) ,
IN INRESPONSABLE VARCHAR(100) ,
IN INOBSERVACIONES VARCHAR(100),
IN ININGRESADO_POR VARCHAR(100),
IN INMODIFICADO_POR VARCHAR(100)
)
BEGIN

     DECLARE CONTADOR INT;
   
     SELECT COUNT(*) INTO CONTADOR FROM REEVALUACION WHERE NROEXPSEYCI = INNROEXPSEYCI;

    IF ( CONTADOR = 0 ) THEN

     INSERT INTO REEVALUACION(NROEXPSEYCI,FECHAINGRESOBENEFICIOS,TIPODOCUMENTO,FECHAEVALUACION,ANALISTA,FECHANOTIFICACION,RESPONSABLE,OBSERVACIONES,INGRESADO_POR,INGRESADO_FECHA)
     VALUES(INNROEXPSEYCI,INFECHAINGRESOBENEFICIOS,INTIPODOCUMENTO,INFECHAEVALUACION,INANALISTA,INFECHANOTIFICACION,INRESPONSABLE,INOBSERVACIONES,ININGRESADO_POR , NOW() );

    ELSE

      UPDATE REEVALUACION SET
       FECHAINGRESOBENEFICIOS = INFECHAINGRESOBENEFICIOS ,
       TIPODOCUMENTO = INTIPODOCUMENTO,
       FECHAEVALUACION = INFECHAEVALUACION ,
       ANALISTA = INANALISTA,
       FECHANOTIFICACION = INFECHANOTIFICACION,
       RESPONSABLE = INRESPONSABLE,
       OBSERVACIONES = INOBSERVACIONES,
       MODIFICADO_POR = INMODIFICADO_POR,
       MODIFICADO_FECHA = NOW()
     WHERE NROEXPSEYCI= INNROEXPSEYCI;

    END IF;

   END;
/*
--Cambios en SP_INSERT_UPDATE_DICTAMEN MODIFICADO_POR , MODIFICADO_FECHA
*/
DROP PROCEDURE  IF EXISTS SP_INSERT_UPDATE_DICTAMEN;
CREATE PROCEDURE `SP_INSERT_UPDATE_DICTAMEN`(
IN INNROEXPSEYCI VARCHAR(100) ,
IN INFECRECAFP VARCHAR(100) ,
IN INFECEMISION VARCHAR(100) ,
IN ININSTANCIA VARCHAR(100) ,
IN INNROEVALUACION VARCHAR(100) ,
IN INDICTAMEN VARCHAR(100) ,
IN INPORCMENOSCABO VARCHAR(100) ,
IN INCALIFICA VARCHAR(100) ,
IN ININDENF VARCHAR(100) ,
IN INDEFINITIVO VARCHAR(100) ,
IN INGRADO VARCHAR(100) ,
IN INNATURALEZA VARCHAR(100) ,
IN INMESES VARCHAR(100) ,
IN INFECINICIAL VARCHAR(100) ,
IN INFECFINAL VARCHAR(100) ,
IN INFECOCURRENCIA VARCHAR(100) ,
IN INPROXIMAEVALUACION VARCHAR(100) ,
IN INFECNOTIFICACION VARCHAR(100) ,
IN INFECRECNOTIFICACION VARCHAR(100) ,
IN INEDAD VARCHAR(100) ,
IN INANALISTA  VARCHAR(100),
IN INOBSERVACIONES VARCHAR(100),
IN INMODIFICADOPOR VARCHAR(100) 
)
BEGIN

     DECLARE CONTADOR INT;
   
     SELECT COUNT(*) INTO CONTADOR FROM SEYCI WHERE EXP = INNROEXPSEYCI;

    #IF ( CONTADOR = 0 ) THEN

     #INSERT INTO TRASLADOSEYCI(NROEXPSEYCI,NROTRASLADO,FECHACITA,ACOMPANANTE,TIPO,ORIGEN,DESTINO,FECHAAPROBACION,MONEDA1,TIPOMOVILIDAD,MONTOMOVILIDAD,MONEDA2,DIASALIMENTACION,MONTOALIMENTACION,MONTO3,DIASALOJAMIENTO,MONTOALOJAMIENTO,MONTOEXTRAMEDICOS,TOTALGASTO,EJECUTIVA,ANALISTA)
     #VALUES(INNROEXPSEYCI,INNROTRASLADO,INFECHACITA,INACOMPANANTE,INTIPO,INORIGEN,INDESTINO,INFECHAAPROBACION,INMONEDA1,INTIPOMOVILIDAD,INMONTOMOVILIDAD,INMONEDA2,INDIASALIMENTACION,INMONTOALIMENTACION,INMONTO3,INDIASALOJAMIENTO,INMONTOALOJAMIENTO,INMONTOEXTRAMEDICOS,INTOTALGASTO,INEJECUTIVA,INANALISTA);

    #ELSE

      UPDATE SEYCI SET
           FECHARECEPCION1 = INFECRECAFP,
           FECHADEEMISION1 = INFECEMISION,
           ENTIDADEVALUADORA1 = ININSTANCIA,
           NRODEEVALUACION1 = INNROEVALUACION,
           NRODICTAMENCOMAFP = INDICTAMEN,
           PORCMENOSCABOASIGNADO1 = INPORCMENOSCABO,
           CALIFICA = INCALIFICA,
           CALIFICACIONINVALIDEZ1 = ININDENF,
           INDICADORDEDEFINITIVO1 = INDEFINITIVO,
           GRADO2 = INGRADO,
           NATURALEZA1 = INNATURALEZA,
           MESES1 = INMESES,
           FECHAINICIOVIGENCIA1	= INFECINICIAL,
           FECHAFINVIGENCIA1 = INFECFINAL,
           FECHAOCURRENCIA1 = INFECOCURRENCIA,
           FECHAPROXIMAEVALUACION1 = INPROXIMAEVALUACION,
           FECHANOTIFAFILIADO = INFECNOTIFICACION,
           FECHARECEPCNOTAFILIADO = INFECRECNOTIFICACION,
           ANALISTA = INANALISTA,
           OBSERVACION = INOBSERVACIONES,
           MODIFICADO_POR = INMODIFICADOPOR,
           MODIFICADO_FECHA = NOW()
        WHERE EXP = INNROEXPSEYCI;



    #END IF;

   END;
/*
--Cambios en SP_INSERT_UPDATE_APELACION MODIFICADO_POR , MODIFICADO_FECHA
*/   
DROP PROCEDURE  IF EXISTS SP_INSERT_UPDATE_APELACION;
CREATE PROCEDURE `SP_INSERT_UPDATE_APELACION`(
IN INNROEXPSEYCI VARCHAR(100) ,
IN INNRODICTAMENAPELADO VARCHAR(100) ,
IN INPERSONAAPELA VARCHAR(100) ,
IN INFECHAAPELACION VARCHAR(100) ,
IN INFECINGBENEFICIOS VARCHAR(100) ,
IN INFECENVIOCARTA VARCHAR(100) ,
IN INRECEPCIONCOMAFP VARCHAR(100) ,
IN INANALISTA VARCHAR(100) ,
IN INMOTIVOAPELACION VARCHAR(100) ,
IN INNROEXPDICTAMEN VARCHAR(100) ,
IN INDISPACIFICO VARCHAR(100) ,
IN INFECHADICTAMEN VARCHAR(100) ,
IN INFECHAENVIODIS VARCHAR(100) ,
IN INOK VARCHAR(100) ,
IN INFECHANOTIFICACIONAFILIADO VARCHAR(100) ,
IN INFECHANOTIFICACIONCOMEC VARCHAR(100) ,
IN INOBSERVACIONES VARCHAR(100),
IN INMODIFICADOPOR VARCHAR(100) 
)
BEGIN

     DECLARE CONTADOR INT;
   
     SELECT COUNT(*) INTO CONTADOR FROM SEYCI WHERE EXP = INNROEXPSEYCI;

      UPDATE SEYCI SET
         ENTIDADQUEAPELA = INPERSONAAPELA,
         MOTIVOAPELACION = INMOTIVOAPELACION,
         MODIFICADO_POR = INMODIFICADOPOR,
         MODIFICADO_FECHA = NOW()
     WHERE EXP = INNROEXPSEYCI;


   END;


