DROP PROCEDURE IF EXISTS SP_LISTAR_DICTAMEN;
CREATE PROCEDURE `SP_LISTAR_DICTAMEN`(
IN INIDSOLICITUD VARCHAR(10)
)
BEGIN

     SELECT 
       IDSEYCI,
           EXP,
           FECHARECEPCION1 FECRECAFP,
           FECHADEEMISION1 FECEMISION,
           ENTIDADEVALUADORA1 INSTANCIA,
           NRODEEVALUACION1 NROEVALUACION,
           NRODICTAMENCOMAFP,
           PORCMENOSCABOASIGNADO1,
           CALIFICA,
           CALIFICACIONINVALIDEZ1 IND_ENF_TER_CANC,
           INDICADORDEDEFINITIVO1 DEFINITIVO,
           GRADO2 GRADO,
           NATURALEZA1 NATURALEZA,
           MESES1 MESES,
           FECHAINICIOVIGENCIA1	FECINICIAL,
           FECHAFINVIGENCIA1 FECFINAL,
           FECHAOCURRENCIA1 FECOCURRENCIA,
           FECHAPROXIMAEVALUACION1 PROXIMAEVALUACION,
           FECHANOTIFAFILIADO,
           FECHARECEPCNOTAFILIADO,
           TIMESTAMPDIFF(YEAR,str_to_date(FechaNacEVALUADO, '%d/%m/%Y'),CURDATE()) AS EDAD,
           ANALISTA,
           OBSERVACION
     FROM SEYCI WHERE EXP=INIDSOLICITUD;

    

   END;
