CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_ACTUALIZAR_SEYCI_DG`(
IN INIDSOLICITUD VARCHAR(100),
IN INCUSPP VARCHAR(100),
IN INPRIMERNOMBRE VARCHAR(100),
IN INSEGUNDONOMBRE VARCHAR(100),
IN INPRIMERAPELLIDO VARCHAR(100),
IN INSEGUNDOAPELLIDO  VARCHAR(100),
IN INFECHANACIMIENTO VARCHAR(100),
IN INCORREO VARCHAR(100),
IN INSEXO VARCHAR(100),
IN INTELEFONO VARCHAR(100),
IN INDIRECCIONAFI VARCHAR(100),
IN INDEPARTAMENTOAFI VARCHAR(100),
IN INPROVINCIAFI VARCHAR(100),
IN INDISTRITOAFI VARCHAR(100),
IN MODIFICADOUSU VARCHAR(50)
)
BEGIN

     UPDATE SEYCI SET
     CUSPP = INCUSPP,
     PRIMERNOMBRE = INPRIMERNOMBRE,
     SEGUNDONOMBRE = INSEGUNDONOMBRE,
     PRIMERAPELLIDO = INPRIMERAPELLIDO,
     SEGUNDOAPELLIDO = INSEGUNDOAPELLIDO,
     FECHANACEVALUADO = INFECHANACIMIENTO,
     EMAILAFI = INCORREO,
     SEXO = (SELECT CASE WHEN INSEXO = '1' THEN 'Masculino' ELSE 'Femenino'  END AS SEXO),
     TELEFONOAFI = INTELEFONO,
     DIRECCIONAFI = INDIRECCIONAFI,
     DEPARTAMENTOAFI  = (SELECT DEPARTAMENTO FROM DEPARTAMENTOS WHERE IDDEPARTAMENTO=INDEPARTAMENTOAFI),
     PROVINCIAAFI = (SELECT PROVINCIA FROM PROVINCIAS WHERE IDPROVINCIA=INPROVINCIAFI),
     DISTRITOAFI = (SELECT DISTRITO FROM DISTRITOS WHERE IDDISTRITO = INDISTRITOAFI),
     MODIFICADO_POR = MODIFICADOUSU,
     MODIFICADO_FECHA = NOW()
     WHERE EXP= INIDSOLICITUD;

   END;
