CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_ACTUALIZAR_SEYCI_TAB`(
IN INIDSOLICITUD VARCHAR(100),
IN INEJECUTIVAAGENCIA VARCHAR(100),
IN INTIPOSOLICITUD VARCHAR(100),
IN INTIPODEEVALUADO VARCHAR(100),
IN INPRIMERNOMBRE VARCHAR(100),
IN INSEGUNDONOMBRE VARCHAR(100),
IN INPRIMERAPELLIDO VARCHAR(100),
IN INSEGUNDOAPELLIDO VARCHAR(100),
IN INFECHANACEVALUADO VARCHAR(100),
IN INFECHASECCIONI VARCHAR(100),
IN INFECHAENVIOCOMAFP VARCHAR(100),
IN INOBSERVACIONESSEYCI VARCHAR(100),
IN MODIFICADOUSU VARCHAR(50)
)
BEGIN

     UPDATE SEYCI SET
     EJECUTIVAAGENCIA = INEJECUTIVAAGENCIA,
     TIPOSOLICITUD  = INTIPOSOLICITUD,
     TIPODEEVALUADO = INTIPODEEVALUADO,
     PRIMERNOMBRE = INPRIMERNOMBRE,
     SEGUNDONOMBRE = INSEGUNDONOMBRE,
     PRIMERAPELLIDO = INPRIMERAPELLIDO,
     SEGUNDOAPELLIDO = INSEGUNDOAPELLIDO,
     FECHANACEVALUADO = INFECHANACEVALUADO,
     FECHASECCIONI = INFECHASECCIONI,
     FECHAENVIOCOMAFP = INFECHAENVIOCOMAFP,
     OBSERVACIONESSEYCI = INOBSERVACIONESSEYCI,
     MODIFICADO_POR = MODIFICADOUSU,
     MODIFICADO_FECHA = NOW()
     WHERE EXP= INIDSOLICITUD;

   END;
