CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_INSERT_UPDATE_TRASLADO`(
IN INNROEXPSEYCI VARCHAR(100) ,
IN INNROTRASLADO VARCHAR(100) ,
IN INFECHACITA VARCHAR(100) ,
IN INACOMPANANTE VARCHAR(100) ,
IN INTIPO VARCHAR(100) ,
IN INORIGEN VARCHAR(100) ,
IN INDESTINO VARCHAR(100) ,
IN INFECHAAPROBACION VARCHAR(100) ,
IN INMONEDA1 VARCHAR(100) ,
IN INTIPOMOVILIDAD VARCHAR(100) ,
IN INMONTOMOVILIDAD VARCHAR(100) ,
IN INMONEDA2 VARCHAR(100) ,
IN INDIASALIMENTACION VARCHAR(100) ,
IN INMONTOALIMENTACION VARCHAR(100) ,
IN INMONTO3 VARCHAR(100) ,
IN INDIASALOJAMIENTO VARCHAR(100) ,
IN INMONTOALOJAMIENTO VARCHAR(100) ,
IN INMONTOEXTRAMEDICOS VARCHAR(100) ,
IN INTOTALGASTO VARCHAR(100) ,
IN INEJECUTIVA VARCHAR(100) ,
IN INANALISTA  VARCHAR(100),
IN MODIFICADOUSU VARCHAR(50)
)
BEGIN

     DECLARE CONTADOR INT;
   
     SELECT COUNT(*) INTO CONTADOR FROM TRASLADOSEYCI WHERE NROEXPSEYCI = INNROEXPSEYCI;

    #IF ( CONTADOR = 0 ) THEN

     INSERT INTO TRASLADOSEYCI(
     NROEXPSEYCI,
     NROTRASLADO,
     FECHACITA,
     ACOMPANANTE,
     TIPO,
     ORIGEN,
     DESTINO,
     FECHAAPROBACION,
     MONEDA1,
     TIPOMOVILIDAD,
     MONTOMOVILIDAD,
     MONEDA2,
     DIASALIMENTACION,
     MONTOALIMENTACION,
     MONTO3,
     DIASALOJAMIENTO,
     MONTOALOJAMIENTO,
     MONTOEXTRAMEDICOS,
     TOTALGASTO,
     EJECUTIVA,
     ANALISTA,
     MODIFICADO_POR,
     MODIFICADO_FECHA)
     VALUES(
     INNROEXPSEYCI,
     INNROTRASLADO,
     INFECHACITA,
     INACOMPANANTE,
     INTIPO,
     INORIGEN,
     INDESTINO,
     INFECHAAPROBACION,
     INMONEDA1,
     INTIPOMOVILIDAD,
     INMONTOMOVILIDAD,
     INMONEDA2,
     INDIASALIMENTACION,
     INMONTOALIMENTACION,
     INMONTO3,
     INDIASALOJAMIENTO,
     INMONTOALOJAMIENTO,
     INMONTOEXTRAMEDICOS,
     INTOTALGASTO,
     INEJECUTIVA,
     INANALISTA,
     MODIFICADOUSU,
     NOW());

    /*ELSE

      UPDATE TRASLADOSEYCI SET
            NROTRASLADO = INNROTRASLADO  ,
            FECHACITA = INFECHACITA  ,
            ACOMPANANTE = INACOMPANANTE  ,
            TIPO = INTIPO  ,
            ORIGEN =  INORIGEN  ,
            DESTINO = INDESTINO  ,
            FECHAAPROBACION = INFECHAAPROBACION  ,
            MONEDA1 = INMONEDA1  ,
            TIPOMOVILIDAD = INTIPOMOVILIDAD  ,
            MONTOMOVILIDAD = INMONTOMOVILIDAD  ,
            MONEDA2 = INMONEDA2  ,
            DIASALIMENTACION = INDIASALIMENTACION  ,
            MONTOALIMENTACION = INMONTOALIMENTACION  ,
            MONTO3 = INMONTO3  ,
            DIASALOJAMIENTO = INDIASALOJAMIENTO  ,
            MONTOALOJAMIENTO = INMONTOALOJAMIENTO  ,
            MONTOEXTRAMEDICOS = INMONTOEXTRAMEDICOS  ,
            TOTALGASTO = INTOTALGASTO  ,
            EJECUTIVA = INEJECUTIVA  ,
            ANALISTA =  INANALISTA
     WHERE NROEXPSEYCI= INNROEXPSEYCI;

    END IF;*/

   END;
